### ISSUE TITLE
CSV only importing 6 Items at a time. 

### ISSUE THREAD

**Issue by mcarring** [omeka/plugin-CsvImport#63] opened 2015-03-19 23:31 UTC
Hello,

We are importing items into Omeka 2.1.4 using CSV  Import
Version 2.0.2 and once we try to import ten or so items we get the error below. CSV is successfully importing up to 6 items at present but we need to import more. The PHP version we are using is 5.4.34

Fatal error: Allowed memory size of 134217728 bytes exhausted (tried to allocate 4294963953 bytes) in ....../Zend/File/Transfer/Adapter/Abstract.php on line 1302

Any ideas?

**Comment by samalloing** [comment] 2015-03-20 10:49
It is strange you run out of memory so soon.

I don't know if is works in 2.0, but you can increase the memory in the CSV plugin if you the following to the config.ini of omeka

plugins.CsvImport.memoryLimit = "256M"

Other settings you can try:
plugins.CsvImport.maxFileSize = "10M"
plugins.CsvImport.batchSize = "10"

**Comment by mcarring** [comment] 2015-03-23 19:29
Hello, 

Is the config.ini for omeka the one located at /omeka/application/config.ini ?

My CsvImportPlugin.php files suggests using 

* <code>
* plugins.CsvImport.columnDelimiter = ","
* plugins.CsvImport.memoryLimit = "128M"
* plugins.CsvImport.requiredExtension = "txt"
* plugins.CsvImport.requiredMimeType = "text/csv"
* plugins.CsvImport.maxFileSize = "10M"
* plugins.CsvImport.fileDestination = "/tmp"
* plugins.CsvImport.batchSize = "1000"
* </code>

**Comment by zerocrates** [comment] 2015-04-19 02:17
From the [release notes for PHP 5.6.8](http://php.net/ChangeLog-5.php#5.6.8) which was just released, it looks like the PHP issue underlying this problem has been fixed.

If you can upgrade your server's PHP version to 5.6.8, I recommend that as the likely solution.

**Comment by zerocrates** [comment] 2015-04-19 02:21
To clarify, the problem is reported as fixed on the newest releases of PHP 5.4, 5.5, and 5.6. The relevant versions are 5.4.40, 5.5.24, and 5.6.8.

**Comment by mcarring** [comment] 2015-04-21 20:11
The version we are using is 5.4.39 (cgi-fcgi) We are getting the import problem with this version. Do you recommend upgrading to PHP 5.6.8?

Mary

**Comment by zerocrates** [comment] 2015-04-21 20:19
The fix appeared on the 5.4, 5.5, and 5.6 branches, you just need a recent enough version within each to get the fix. So, 5.4.40 will work, but 5.5.23 will not (it needs to be 5.5.24 or higher within the 5.5 series).

Bottom line, upgrading to any of 5.4.40, 5.5.24, or 5.6.8 should fix this problem. 5.4.40 should be a drop-in replacement that merely fixes bugs (including this one) without having much of any potential to cause problems. 5.6.8 is in some ways the optimal choice, but not a necessary one, with a slightly higher possibility for incompatibilities with stuff you're already running. Omeka should work with any of those versions.

**Closed** 2016-07-27 17:43 UTC
